export const TAXONOMY = {
  categories: [
    {
      id: 'cricket',
      name: 'Cricket',
      icon: '🏏',
      streamPrefix: 'sport:cricket',
      subcategories: [
        { id: 'ipl', name: 'IPL', stream: 'sport:cricket:ipl' },
        { id: 'international', name: 'International', stream: 'sport:cricket:international' },
        { id: 'psl', name: 'PSL', stream: 'sport:cricket:psl' },
        { id: 't20wc', name: 'T20 World Cup', stream: 'sport:cricket:t20wc' },
        { id: 'test', name: 'Test Series', stream: 'sport:cricket:test' },
        { id: 'women', name: "Women's Cricket", stream: 'sport:cricket:women' },
        { id: 'ct', name: 'Champions Trophy', stream: 'sport:cricket:ct' },
      ],
      marketTypes: ['match_winner', 'top_batsman', 'top_bowler', 'totals', 'futures'],
    },
    {
      id: 'soccer',
      name: 'Soccer',
      icon: '⚽',
      streamPrefix: 'sport:soccer',
      subcategories: [
        { id: 'epl', name: 'EPL', stream: 'sport:soccer:epl' },
        { id: 'ucl', name: 'Champions League', stream: 'sport:soccer:ucl' },
        { id: 'laliga', name: 'La Liga', stream: 'sport:soccer:laliga' },
        { id: 'bundesliga', name: 'Bundesliga', stream: 'sport:soccer:bundesliga' },
        { id: 'seriea', name: 'Serie A', stream: 'sport:soccer:seriea' },
        { id: 'mls', name: 'MLS', stream: 'sport:soccer:mls' },
        { id: 'worldcup', name: 'World Cup', stream: 'sport:soccer:worldcup' },
        { id: 'copa', name: 'Copa America', stream: 'sport:soccer:copa' },
      ],
      marketTypes: ['match_winner', 'btts', 'correct_score', 'totals', 'futures'],
    },
    {
      id: 'basketball',
      name: 'Basketball',
      icon: '🏀',
      streamPrefix: 'sport:basketball',
      subcategories: [
        { id: 'nba', name: 'NBA', stream: 'sport:basketball:nba' },
        { id: 'ncaab', name: 'NCAAB', stream: 'sport:basketball:ncaab' },
        { id: 'euroleague', name: 'EuroLeague', stream: 'sport:basketball:euroleague' },
        { id: 'wnba', name: 'WNBA', stream: 'sport:basketball:wnba' },
        { id: 'bleague', name: 'Japan B League', stream: 'sport:basketball:bleague' },
        { id: 'bsl', name: 'Turkey BSL', stream: 'sport:basketball:bsl' },
        { id: 'endesa', name: 'Liga Endesa', stream: 'sport:basketball:endesa' },
      ],
      marketTypes: ['moneyline', 'spread', 'totals', 'player_props', 'futures'],
    },
    {
      id: 'nfl',
      name: 'NFL',
      icon: '🏈',
      streamPrefix: 'sport:nfl',
      subcategories: [
        { id: 'superbowl', name: 'Super Bowl', stream: 'sport:nfl:superbowl' },
        { id: 'afc', name: 'AFC', stream: 'sport:nfl:afc' },
        { id: 'nfc', name: 'NFC', stream: 'sport:nfl:nfc' },
        { id: 'mvp', name: 'MVP', stream: 'sport:nfl:mvp' },
        { id: 'draft', name: 'Draft', stream: 'sport:nfl:draft' },
        { id: 'ncaafb', name: 'College Football', stream: 'sport:nfl:ncaafb' },
        { id: 'playoffs', name: 'Playoffs', stream: 'sport:nfl:playoffs' },
        { id: 'wins', name: 'Season wins', stream: 'sport:nfl:wins' },
      ],
      marketTypes: ['moneyline', 'spread', 'totals', 'futures'],
    },
    {
      id: 'baseball',
      name: 'Baseball',
      icon: '⚾',
      streamPrefix: 'sport:baseball',
      subcategories: [
        { id: 'mlb', name: 'MLB', stream: 'sport:baseball:mlb' },
        { id: 'kbo', name: 'KBO', stream: 'sport:baseball:kbo' },
        { id: 'ws', name: 'World Series', stream: 'sport:baseball:ws' },
        { id: 'hr', name: 'Home Runs', stream: 'sport:baseball:hr' },
        { id: 'playoffs', name: 'Playoffs', stream: 'sport:baseball:playoffs' },
        { id: 'stats', name: 'Season stats', stream: 'sport:baseball:stats' },
      ],
      marketTypes: ['moneyline', 'run_line', 'totals', 'player_props', 'futures'],
    },
    {
      id: 'hockey',
      name: 'Hockey',
      icon: '🏒',
      streamPrefix: 'sport:hockey',
      subcategories: [
        { id: 'nhl', name: 'NHL', stream: 'sport:hockey:nhl' },
        { id: 'stanleycup', name: 'Stanley Cup', stream: 'sport:hockey:stanleycup' },
        { id: 'ahl', name: 'AHL', stream: 'sport:hockey:ahl' },
        { id: 'khl', name: 'KHL', stream: 'sport:hockey:khl' },
        { id: 'shl', name: 'Swedish HL', stream: 'sport:hockey:shl' },
      ],
      marketTypes: ['moneyline', 'puck_line', 'totals', 'futures'],
    },
    {
      id: 'tennis',
      name: 'Tennis',
      icon: '🎾',
      streamPrefix: 'sport:tennis',
      subcategories: [
        { id: 'wimbledon', name: 'Wimbledon', stream: 'sport:tennis:wimbledon' },
        { id: 'usopen', name: 'US Open', stream: 'sport:tennis:usopen' },
        { id: 'frenchopen', name: 'French Open', stream: 'sport:tennis:frenchopen' },
        { id: 'ausopen', name: 'Australian Open', stream: 'sport:tennis:ausopen' },
        { id: 'atp', name: 'ATP', stream: 'sport:tennis:atp' },
        { id: 'wta', name: 'WTA', stream: 'sport:tennis:wta' },
      ],
      marketTypes: ['match_winner', 'set_betting', 'futures'],
    },
    {
      id: 'f1',
      name: 'F1',
      icon: '🏎️',
      streamPrefix: 'sport:f1',
      subcategories: [
        { id: 'wdc', name: 'World Champion', stream: 'sport:f1:wdc' },
        { id: 'race', name: 'Race winner', stream: 'sport:f1:race' },
        { id: 'wcc', name: 'Constructor', stream: 'sport:f1:wcc' },
        { id: 'pole', name: 'Pole Position', stream: 'sport:f1:pole' },
        { id: 'standings', name: 'Driver standings', stream: 'sport:f1:standings' },
      ],
      marketTypes: ['race_winner', 'podium_finish', 'futures', 'head_to_head'],
    },
    {
      id: 'combat',
      name: 'MMA & Boxing',
      icon: '🥊',
      streamPrefix: 'sport:combat',
      subcategories: [
        { id: 'ufc', name: 'UFC', stream: 'sport:combat:ufc' },
        { id: 'bellator', name: 'Bellator', stream: 'sport:combat:bellator' },
        { id: 'heavyweight', name: 'Heavyweight title', stream: 'sport:combat:heavyweight' },
        { id: 'ko', name: 'KO/TKO', stream: 'sport:combat:ko' },
        { id: 'title', name: 'Title Fights', stream: 'sport:combat:title' },
      ],
      marketTypes: ['moneyline', 'method_of_victory', 'round_betting', 'futures'],
    },
    {
      id: 'golf',
      name: 'Golf',
      icon: '⛳',
      streamPrefix: 'sport:golf',
      subcategories: [
        { id: 'masters', name: 'Masters', stream: 'sport:golf:masters' },
        { id: 'usopen', name: 'US Open', stream: 'sport:golf:usopen' },
        { id: 'theopen', name: 'The Open', stream: 'sport:golf:theopen' },
        { id: 'pga', name: 'PGA Tour', stream: 'sport:golf:pga' },
        { id: 'rydercup', name: 'Ryder Cup', stream: 'sport:golf:rydercup' },
        { id: 'liv', name: 'LIV Golf', stream: 'sport:golf:liv' },
      ],
      marketTypes: ['tournament_winner', 'top_5', 'top_10', 'head_to_head', 'futures'],
    },
    {
      id: 'esports',
      name: 'Esports',
      icon: '🎮',
      streamPrefix: 'esports',
      subcategories: [
        { id: 'cs2', name: 'CS2', stream: 'esports:cs2' },
        { id: 'lol', name: 'League of Legends', stream: 'esports:lol' },
        { id: 'dota2', name: 'Dota 2', stream: 'esports:dota2' },
        { id: 'valorant', name: 'Valorant', stream: 'esports:valorant' },
        { id: 'fortnite', name: 'Fortnite', stream: 'esports:fortnite' },
      ],
      marketTypes: ['map_winner', 'match_winner', 'tournament_winner', 'handicap'],
    },
    {
      id: 'rugby',
      name: 'Rugby',
      icon: '🏉',
      streamPrefix: 'sport:rugby',
      subcategories: [
        { id: 'sixnations', name: 'Six Nations', stream: 'sport:rugby:sixnations' },
        { id: 'superrugby', name: 'Super Rugby', stream: 'sport:rugby:superrugby' },
        { id: 'worldcup', name: 'World Cup', stream: 'sport:rugby:worldcup' },
        { id: 'top14', name: 'Top 14', stream: 'sport:rugby:top14' },
      ],
      marketTypes: ['match_winner', 'handicap', 'totals', 'tournament_winner'],
    },
    {
      id: 'politics',
      name: 'Politics',
      icon: '🏛️',
      streamPrefix: 'politics',
      subcategories: [
        { id: 'trump', name: 'Trump', stream: 'politics:trump' },
        { id: 'congress', name: 'Congress', stream: 'politics:congress' },
        { id: 'scotus', name: 'SCOTUS', stream: 'politics:scotus' },
        { id: 'whitehouse', name: 'White House', stream: 'politics:whitehouse' },
        { id: 'iran', name: 'Iran', stream: 'politics:iran' },
        { id: 'immigration', name: 'Immigration', stream: 'politics:immigration' },
        { id: 'policy', name: 'Policy', stream: 'politics:policy' },
      ],
      marketTypes: ['policy_outcome', 'approval', 'futures'],
    },
    {
      id: 'elections',
      name: 'Elections',
      icon: '🗳️',
      streamPrefix: 'elections',
      subcategories: [
        { id: 'us_midterms', name: 'US Midterms', stream: 'elections:us:midterms' },
        { id: 'us_senate', name: 'Senate', stream: 'elections:us:senate' },
        { id: 'us_house', name: 'House', stream: 'elections:us:house' },
        { id: 'india', name: 'India', stream: 'elections:india' },
        { id: 'uk', name: 'UK', stream: 'elections:uk' },
        { id: 'eu', name: 'EU', stream: 'elections:eu' },
        { id: 'germany', name: 'Germany', stream: 'elections:germany' },
        { id: 'global', name: 'Global', stream: 'elections:global' },
      ],
      marketTypes: ['seat_winner', 'party_control', 'futures'],
    },
    {
      id: 'crypto',
      name: 'Crypto',
      icon: '₿',
      streamPrefix: 'crypto',
      subcategories: [
        { id: 'btc', name: 'Bitcoin', stream: 'crypto:btc' },
        { id: 'eth', name: 'Ethereum', stream: 'crypto:eth' },
        { id: 'sol', name: 'Solana', stream: 'crypto:sol' },
        { id: 'alts', name: 'Altcoins', stream: 'crypto:alts' },
        { id: 'defi', name: 'DeFi', stream: 'crypto:defi' },
        { id: 'etf', name: 'ETF', stream: 'crypto:etf' },
        { id: 'regulation', name: 'Regulation', stream: 'crypto:regulation' },
        { id: 'xrp', name: 'XRP', stream: 'crypto:xrp' },
      ],
      marketTypes: ['price_target', 'above_below', 'legal_outcome', 'futures'],
    },
    {
      id: 'economics',
      name: 'Economics',
      icon: '📊',
      streamPrefix: 'economics',
      subcategories: [
        { id: 'fed', name: 'Fed rates', stream: 'economics:fed' },
        { id: 'inflation', name: 'Inflation', stream: 'economics:inflation' },
        { id: 'gdp', name: 'GDP', stream: 'economics:gdp' },
        { id: 'unemployment', name: 'Unemployment', stream: 'economics:unemployment' },
        { id: 'recession', name: 'Recession', stream: 'economics:recession' },
        { id: 'tariffs', name: 'Tariffs', stream: 'economics:tariffs' },
        { id: 'cpi', name: 'CPI', stream: 'economics:cpi' },
      ],
      marketTypes: ['rate_decision', 'above_below', 'futures'],
    },
    {
      id: 'companies',
      name: 'Companies',
      icon: '🏢',
      streamPrefix: 'companies',
      subcategories: [
        { id: 'earnings', name: 'Earnings', stream: 'companies:earnings' },
        { id: 'ma', name: 'M&A', stream: 'companies:ma' },
        { id: 'ipo', name: 'IPOs', stream: 'companies:ipo' },
        { id: 'bigtech', name: 'Big Tech', stream: 'companies:bigtech' },
        { id: 'ceo', name: 'CEO changes', stream: 'companies:ceo' },
        { id: 'stocks', name: 'Stock targets', stream: 'companies:stocks' },
        { id: 'layoffs', name: 'Layoffs', stream: 'companies:layoffs' },
      ],
      marketTypes: ['beat_miss', 'eps', 'deal_outcome', 'futures'],
    },
    {
      id: 'tech',
      name: 'Tech & AI',
      icon: '🤖',
      streamPrefix: 'tech',
      subcategories: [
        { id: 'aimodels', name: 'AI Models', stream: 'tech:aimodels' },
        { id: 'openai', name: 'OpenAI', stream: 'tech:openai' },
        { id: 'semis', name: 'Semiconductors', stream: 'tech:semis' },
        { id: 'space', name: 'Space', stream: 'tech:space' },
        { id: 'biotech', name: 'Biotech', stream: 'tech:biotech' },
        { id: 'regulation', name: 'Regulation', stream: 'tech:regulation' },
        { id: 'startups', name: 'Startups', stream: 'tech:startups' },
      ],
      marketTypes: ['launch_outcome', 'fda_approval', 'benchmark', 'futures'],
    },
    {
      id: 'world',
      name: 'World',
      icon: '🌍',
      streamPrefix: 'world',
      subcategories: [
        { id: 'middleeast', name: 'Middle East', stream: 'world:middleeast' },
        { id: 'ukraine', name: 'Ukraine', stream: 'world:ukraine' },
        { id: 'china', name: 'China', stream: 'world:china' },
        { id: 'nato', name: 'NATO', stream: 'world:nato' },
        { id: 'tradewars', name: 'Trade Wars', stream: 'world:tradewars' },
        { id: 'indpak', name: 'India-Pakistan', stream: 'world:indpak' },
        { id: 'sanctions', name: 'Sanctions', stream: 'world:sanctions' },
      ],
      marketTypes: ['geopolitical_outcome', 'policy_outcome', 'futures'],
    },
    {
      id: 'culture',
      name: 'Culture',
      icon: '🎭',
      streamPrefix: 'culture',
      subcategories: [
        { id: 'oscars', name: 'Oscars', stream: 'culture:oscars' },
        { id: 'emmys', name: 'Emmys', stream: 'culture:emmys' },
        { id: 'grammy', name: 'Grammy', stream: 'culture:grammy' },
        { id: 'boxoffice', name: 'Box Office', stream: 'culture:boxoffice' },
        { id: 'celebrity', name: 'Celebrity', stream: 'culture:celebrity' },
        { id: 'tvfilm', name: 'TV & Film', stream: 'culture:tvfilm' },
        { id: 'viral', name: 'Viral moments', stream: 'culture:viral' },
      ],
      marketTypes: ['award_winner', 'opening_weekend', 'futures'],
    },
    {
      id: 'science',
      name: 'Science',
      icon: '🔬',
      streamPrefix: 'science',
      subcategories: [
        { id: 'space', name: 'Space missions', stream: 'science:space' },
        { id: 'climate', name: 'Climate', stream: 'science:climate' },
        { id: 'fda', name: 'FDA approvals', stream: 'science:fda' },
        { id: 'pandemics', name: 'Pandemics', stream: 'science:pandemics' },
        { id: 'energy', name: 'Energy', stream: 'science:energy' },
        { id: 'nuclear', name: 'Nuclear', stream: 'science:nuclear' },
      ],
      marketTypes: ['launch_outcome', 'approval', 'above_below', 'futures'],
    },
  ],
}
